steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dev-proxy:$BUILD_ID', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dev-proxy:$BUILD_ID']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dev-proxy'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dev-proxy:$BUILD_ID'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'TAILSCALE_OAUTH_CLIENT_ID=TAILSCALE_OAUTH_CLIENT_ID:latest,TAILSCALE_OAUTH_CLIENT_SECRET=TAILSCALE_OAUTH_CLIENT_SECRET:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/dev-proxy:$BUILD_ID'
